src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class)
            ->add('message', TextareaType::class)
            ->add('recipient', EntityType::class, [
                "class" => User::class,
                "choice_label" => "email"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MessageController extends AbstractController
{
    /**
     * @Route("/profile/message", name="app_message")
     */
    public function index(): Response
    {
        return $this->render('message/index.html.twig', [
            'controller_name' => 'MessageController',
        ]);
    }

    /**
     * @Route("/send", name="app_send")
     */
    public function sendMessage(ManagerRegistry $doctrine, Request $request) : Response
    {
        $message = new Message;
        
        $form = $this->createForm(MessageType::class, $message);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $message->setSender($this->getUser());

            $messageManager = $doctrine->getManager();
            $messageManager->persist($message);
            $messageManager->flush();

            $this->addFlash(
                'message',
                "Votre message a bien été envoyé"
            );

            return $this->redirectToRoute('app_message');
        }

        return $this->render('message/sendMessage.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/inbox", name="app_inbox")
     */
    public function inbox(): Response
    {
        return $this->render('message/inbox.html.twig');
    }

    /**
     * @Route("/read/{id}", name="app_read")
     */
    public function readMessage(ManagerRegistry $doctrine, Message $message): Response
    {
        $message->setIsRead(true);
        $messageManager = $doctrine->getManager();

        $messageManager->persist($message);
        $messageManager->flush();

        return $this->render('message/read.html.twig', compact("message"));
    }

    /**
     * @Route("/delete/{id}", name="app_delete")
     */
    public function deleteMessage(ManagerRegistry $doctrine, Message $message): Response
    {
        $messageManager = $doctrine->getManager();

        $messageManager->remove($message);
        $messageManager->flush();

        return $this->redirectToRoute("app_inbox");
    }
    
    /**
     * @Route("/sent", name="app_sent")
     */
    public function sentMessages()
    {
        return $this->render('message/sent.html.twig');
    }

}   

templates/message/inbox.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}

<section id="inbox">

    {% for message in app.flashes('message') %}
        <div class="alert-warning text-center mb-3">
            {{ message }}
            <i class="fa-solid fa-thumbs-up"></i>
        </div>
    {% endfor %}

    <h1>Boite de réception</h1>
    {# <div class="row justify-content-between mb-5">
        <a class="btn btn-primary btn-return" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
            Menu
        </a>

        <a href="{{ path('app_send') }}" class="btn btn-dark btn-return">Nouveau message</a>
    </div> #}

    <table class="table table-hover mt-5">
        <thead>
          <tr>
            <th scope="col">Expéditeur</th>
            <th scope="col">Objet</th>
            <th scope="col">Aperçu du message</th>
            <th scope="col">Date de réception</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
        {% for message in app.user.received %}

            {% if message.isRead == 0 %}
                {% set bold = "fw-bold" %}
            {% else %}
                {% set bold = "" %}
            {% endif %}

            <tr class="{{bold}}">
                <td>{{message.sender.email}}</td>
                <td>
                    <a class="blue-hover" href="{{ path('app_read', {'id': message.id}) }}">
                        {{message.title}}
                    </a>
                </td>
                <td class="message-preview">
                    <a class="blue-hover" href="{{ path('app_read', {'id': message.id}) }}">{{message.message | u.truncate(45, '...', false) }}</a>
                </td>
                <td>{{message.createdat | date ("d/m/Y")}}</td>
                <td>
                    <a href="{{ path('app_delete', {'id': message.id}) }}" onclick="return confirm('Etes vous sûr de vouloir supprimer ce message ?')">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>

    {# Menu latéral de la messagerie #}
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
            <h2 class="offcanvas-title" id="offcanvasExampleLabel">Menu</h2>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            
            <a href="{{ path('app_send') }}" class="btn btn-dark mb-4 btn-return">Nouveau message</a>
            
            <ul class="list-group">
                <a href="{{ path('app_message') }}" class="list-group-item">
                    Accueil
                </a>
           
                <a href="{{ path('app_inbox') }}" class="list-group-item active">
                    Boîte de réception
                </a>
            
                <a href="{{ path('app_sent') }}" class="list-group-item">
                    Eléments envoyés
                </a>
            </ul>
        </div>
    </div>

</section>
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}

<section id="messagerie">

    {% for message in app.flashes('message') %}
        <div class="alert-warning text-center mb-3">
            {{ message }}
            <i class="fa-solid fa-thumbs-up"></i>
        </div>
    {% endfor %}

    <h1>Messagerie</h1>
    <p class="fw-bold mt-5">Résumé de la messagerie :</p>
    <p>Nombre de messages reçus : {{ app.user.received|length}}</p>
    <p>Nombre de messages envoyés : {{app.user.sent|length}}</p>
    {# <a class="btn btn-primary btn-return me-2" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        Menu
    </a>

    <a href="{{ path('app_send') }}" class="btn btn-dark btn-return">Nouveau message</a> #}
    
    {# Menu latéral de la messagerie #}
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
            <h2 class="offcanvas-title" id="offcanvasExampleLabel">Menu</h2>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            
            <a href="{{ path('app_send') }}" class="btn btn-dark mb-4 btn-return">Nouveau message</a>
            
            <ul class="list-group">
                <a href="{{ path('app_message') }}" class="list-group-item active">
                    Accueil
                </a>
           
                <a href="{{ path('app_inbox') }}" class="list-group-item">
                    Boîte de réception
                </a>
            
                <a href="{{ path('app_sent') }}" class="list-group-item">
                    Eléments envoyés
                </a>
            </ul>
        </div>
    </div>

</section>
{% endblock %}

templates/message/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}

<section id="read">

    {% for message in app.flashes('message') %}
        <div class="alert-warning text-center mb-3">
            {{ message }}
            <i class="fa-solid fa-thumbs-up"></i>
        </div>
    {% endfor %}

    <h2>Objet: {{message.title}}</h2>
    <p> 
        <span class="fw-bold">Expéditeur :</span> {{message.sender.email}}
    </p>
    <p>
        <span class="fw-bold">Reçu le :</span> {{message.createdat | format_datetime ("full", 'short', locale='fr') }}
    </p> 
    
    <p>
        <span class="fw-bold">Contenu du message :</span>
            <div class="msg-container">
                {{message.message}}
            </div>
    </p>
    
    <a class="btn btn-primary me-2 btn-action" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        Menu
    </a>

    <a href="{{ path('app_inbox') }}" class="btn btn-dark btn-action">Retour à la boîte de réception</a>

    {# Menu latéral de la messagerie #}
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
            <h2 class="offcanvas-title" id="offcanvasExampleLabel">Menu</h2>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            
            <a href="{{ path('app_send') }}" class="btn btn-dark mb-4 btn-return">Nouveau message</a>
            
            <ul class="list-group">
                <a href="{{ path('app_message') }}" class="list-group-item">
                    Accueil
                </a>
           
                <a href="{{ path('app_inbox') }}" class="list-group-item active">
                    Boîte de réception
                </a>
            
                <a href="{{ path('app_sent') }}" class="list-group-item">
                    Eléments envoyés
                </a>
            </ul>
        </div>
    </div>

</section>
{% endblock %}

templates/message/sendMessage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Envoyer un message{% endblock %}

{% block body %}
<h1>Envoi d'un nouveau message</h1>

<section id="send-msg" class="py-5">
    {{ form_start(form, {'attr': {'class': 'd-flex flex-column gap-3 m-auto'}} ) }}
        
        {{ form_row(form.recipient, {'label': 'Destinaire :', 'attr' : {'class' : 'form-control' }} )}}

        {{ form_row(form.title, {'label': 'Objet :', 'attr' : {'class' : 'form-control' }} ) }}

        {{ form_row(form.message, {'label': 'Contenu du message :', 'attr' : {'class' : 'form-control py-5' }} ) }}

    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-success btn-action me-5">Envoyer le message</button>
        {# <a href="{{ path('app_inbox') }}" class="btn btn-primary btn-action">Retour à la boîte de réception</a> #}
    </div>
    {{ form_end(form) }}
</section>

{% endblock %}

templates/message/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}

<section id="inbox">

    {% for message in app.flashes('message') %}
        <div class="alert-warning text-center mb-3">
            {{ message }}
            <i class="fa-solid fa-thumbs-up"></i>
        </div>
    {% endfor %}

    <h1>Messages envoyés</h1>
    
    {# <div class="row justify-content-between mb-5">
        <a class="btn btn-primary btn-return" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
            Menu
        </a>

        <a href="{{ path('app_send') }}" class="btn btn-dark btn-return">Nouveau message</a>
    </div> #}
    
    <table class="table table-hover mt-5">
        <thead>
          <tr>
            <th scope="col">Destinaire</th>
            <th scope="col">Objet</th>
            <th scope="col">Aperçu du message</th>
            <th scope="col">Date d'envoi</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
        {% for message in app.user.sent %}

            <tr>
                <td>{{message.recipient.email}}</td>
                <td>
                    <a class="blue-hover" href="{{ path('app_read', {'id': message.id}) }}">
                        {{message.title}}
                    </a>
                </td>
                <td class="message-preview">
                    <a class="blue-hover" href="{{ path('app_read', {'id': message.id}) }}">{{message.message | u.truncate(45, '...', false) }}</a>
                </td>
                <td>{{message.createdat | date ("d/m/Y")}}</td>
                <td>
                    <a href="{{ path('app_delete', {'id': message.id}) }}" onclick="return confirm('Etes vous sûr de vouloir supprimer ce message ?')">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>

    {# Menu latéral de la messagerie #}
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
            <h2 class="offcanvas-title" id="offcanvasExampleLabel">Menu</h2>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            
            <a href="{{ path('app_send') }}" class="btn btn-dark mb-4 btn-return">Nouveau message</a>
            
            <ul class="list-group">
                <a href="{{ path('app_message') }}" class="list-group-item">
                    Accueil
                </a>
           
                <a href="{{ path('app_inbox') }}" class="list-group-item">
                    Boîte de réception
                </a>
            
                <a href="{{ path('app_sent') }}" class="list-group-item active">
                    Eléments envoyés
                </a>
            </ul>
        </div>
    </div>

</section>
{% endblock %}